services:
  database:
    image: mysql:8.0
    container_name: kolmox
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kolmox_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql